version: "3.8"
services:
  mongo:
    image: mongo
    networks:  
      - networkmongo    
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - mongo-data:/data/db 
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
      MONGO_INITDB_DATABASE: "workshop_mongo"
  mongo-express:
    image: mongo-express
    networks:  
      - networkmongo
    expose:
      - 8081
    restart: always
    depends_on:
      - mongo
    ports: 
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "mongoadmin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "secret"      
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"  
volumes:
  mongo-data:
    driver: local      
networks: 
  networkmongo: 
    driver: bridge        